### ISSUE TITLE
Intent to implement: State-specific holidays

### ISSUE THREAD

**Issue by koterpillar** [hvianna/desktopCal.js#8]
In [some countries](https://www.fairwork.gov.au/employment-conditions/public-holidays/2023-public-holidays) each state decides their holidays more or less independently. Would you be interested in a PR that adds an optional state selector for those?

**Comment by hvianna** [comment]
I'm thinking of a different approach for this: user selects the country, we load all of that country's holidays and then let the user selectively enable/disable individual holidays via the UI.

**Comment by koterpillar** [comment]
If you look at #9, there are quite a few state-specific holidays (Australia) and it'd be tedious for the user to choose. If we know which holiday applies to which state, why not use that information?

**Comment by hvianna** [comment]
Ok, sure! Please note I'm merging the other in-development features to the `dev` branch, so use that as the base branch, please.

**Comment by koterpillar** [comment]
Thanks, I've based my branch on #10 so will open a PR as soon as that's merged.
